language: csharp
solution: SchoolBasic/SchoolBasic.sln

install:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - nuget restore SchoolBasic/SchoolBasic.sln
  # nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release SchoolBasic-Lib/SchoolBasic.sln

after_success:
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - ./send.sh failure $WEBHOOK_URL